title: Taylor Steinberg
email: taylor@steinberg.xyz
description: >-
  This is the personal blog of Taylor Steinberg
baseurl: "/"
url: "https://blog.taylorsteinberg.com"
twitter_username: tdstein
github_username:  tdstein
google_analytics: UA-143335693-1
show_excerpts: true

disqus:
    shortname: taylor-steinberg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap